---
- name: My Ansible Training File
  hosts: all
  tasks:
     - name: Leaving a mark
       command: "touch /tmp/ansible_was_here"

     - name: install python 
       apt:
         name: python

       state: latest
       update_cache: yes
