---

- hosts: all
  become: true
  tasks:

  - name: install apache , python and php support 
    apt:
      name: 
        - "{{ python_lang }}"
        - "{{ php_package }}"
      state: latest 
      update_cache: yes 
