---

- hosts: all
  become: true
  tasks:

  - name: install apache , python and php support 
    apt:
      name:
         - python
         - libapache2-mod-php
         - apache2 
      state: latest 
      update_cache: yes 
   
  - name: reboot the system 
    reboot:
        reboot_command: reboot   
        reboot_timeout: 3600
    when: ansible_distribution == "CentOS"
  
  
  - name: copy some files in one host 
    ansible.builtin.copy:
            src:  /home/tarokh/Documents/text.txt
            dest: /home/server/Desktop

  - name: shutdown the machine 
    community.general.shutdown:
            delay: 15
               
