---

- hosts: all
  become: true
  tasks:

  - name: install apache , python and php support 
    apt:
      name:
         - python
         - libapache2-mod-php
         - apache2 
      state: latest 
      update_cache: yes 

